EnvGet, THREAD_COUNT, NUMBER_OF_PROCESSORS
EnvGet, USER_PROFILE, USERPROFILE

global MSG_RESET := 0x04E20
global MSG_KILL := 0x04E21
global MSG_TEST := 0x04E22
global MSG_ASSIGN_RMPID := 0x04E23
global MSG_CONFIRM_RM := 0x04E24
global MSG_TEST_RESET := 0x04E25

global LOG_LEVEL_INFO := "INFO"
global LOG_LEVEL_WARNING := "WARN"
global LOG_LEVEL_ERROR := "ERR"

global PREVIEW_FOUND := 1
global INSTANCE_LOADED := 2